services:
  postgres-user:
    container_name: postgres-user
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - skolr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  api-gateaway:
    container_name: api-gateaway
    environment:
      PORT: ${}
    depends_on:
      postgres-user:
        condition: service_healthy
    build:
      context: ./api-gateaway
      dockerfile: Dockerfile
